#!/usr/bin/env bash
#
# Compose the deployment environment dsh actually reads.
#
#   scripts/compose-env.sh              write the composed file
#   scripts/compose-env.sh --dry-run    print what would be written
#
# Why this exists
# ---------------
# The runtime reads two .env layers - the invoking directory's and the harness home's - and applies
# them WITHOUT resolving paths: a value goes into process.env exactly as written. The consumers then
# read it with `process.env.NAME` inside a !!js config expression, so a relative path would never be
# resolved by anything. This script is therefore the one place a relative path becomes absolute.
#
# It also keeps the two halves apart. .env.base holds non-secret values and is committed; the
# secrets directory holds credentials and is ignored by git. Composing them here means the runtime
# sees one file while the repository carries only what is safe to publish.
#
# Sources, in order of increasing precedence (later wins):
#   .env.base            committed, relative paths resolved against the repository root
#   .secrets/env         ignored, verbatim
#
# Names beginning with DSH_, XDG_, DYLD_ or BASH_FUNC_ are refused: app-boot treats those prefixes
# as bootstrap-only and exits the runtime when a .env sets one, so this script fails loudly instead
# of writing a file that cannot boot.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BASE="$REPO_ROOT/.env.base"
SECRETS="$REPO_ROOT/.secrets/env"
OUT="${DSH_ENV_OUT:-/root/.dsh/.env}"
DRY=no
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY=yes ;;
    *) echo "compose-env: unknown argument: $arg" >&2; exit 2 ;;
  esac
done

# A name the runtime would refuse, checked before anything is written.
is_bootstrap_name() {
  case "$1" in
    DSH_*|XDG_*|DYLD_*|BASH_FUNC_*) return 0 ;;
    *) return 1 ;;
  esac
}

# Expand one value: a relative path becomes absolute against the repository root, anything already
# absolute, a URL, or a plain token is passed through. Quoted values keep their quotes stripped.
expand_value() {
  local value="$1"
  case "$value" in
    "/*"|"~"*|http://*|https://*|""|*[!A-Za-z0-9._/-]*) printf '%s' "$value" ;;
    *) printf '%s' "$REPO_ROOT/$value" ;;
  esac
}

emit() {
  local file="$1" label="$2"
  [ -f "$file" ] || return 0
  while IFS= read -r line || [ -n "$line" ]; do
    # Comments and blanks are dropped: the runtime strips them anyway (the capability interview
    # rewrites this file and keeps only assignments), so keeping them here would only pretend the
    # output is hand-editable when it is generated.
    case "$line" in ''|'#'*) continue ;; esac
    local name="${line%%=*}"
    case "$name" in *[!A-Za-z0-9_]*) continue ;; esac
    if is_bootstrap_name "$name"; then
      echo "compose-env: $label defines $name, which the runtime refuses in any .env" >&2
      echo "compose-env: rename it (drop the reserved prefix); see app-boot isBootstrapOnly()" >&2
      exit 3
    fi
    local value="${line#*=}"
    value="${value%\"}"; value="${value#\"}"
    value="${value%\'}"; value="${value#\'}"
    if [ "$label" = base ]; then value="$(expand_value "$value")"; fi
    printf '%s=%s\n' "$name" "$value"
  done < "$file"
}

composed="$( { emit "$BASE" base; emit "$SECRETS" secrets; } )"

if [ -z "$composed" ]; then
  echo "compose-env: nothing to compose (no $BASE and no $SECRETS)" >&2
  exit 1
fi

header="# Generated by scripts/compose-env.sh from .env.base and .secrets/env."
body="$header"$'\n'"# Edit those files, not this one; the next compose overwrites this."$'\n'"$composed"

if [ "$DRY" = yes ]; then
  printf '%s\n' "$body"
  exit 0
fi

install -d -m 700 "$(dirname "$OUT")"
printf '%s\n' "$body" > "$OUT"
chmod 600 "$OUT"
echo "compose-env: wrote $OUT"
printf '%s\n' "$composed" | sed 's/=.*/=<set>/' | sed 's/^/  /'
